---
name: Run all Ansible Playbooks

on:
  push:
  pull_request:
    branches: [master]

jobs:
  run:
    strategy:
      matrix:
        os: [ubuntu-20.04, ubuntu-22.04, ubuntu-24.04]

    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install Ansible
        run: |
          sudo apt update
          sudo apt install -y python3-pip
          python -m pip install --upgrade pip
          pip install ansible

      - name: Run the Ansible Playbook
        run: |
          ansible-playbook -i inventory sectigo-debian-desktop.yml
